Repository haskell/unix, pull requests merged in 2022-07, with the labels that each got.

#224 Improve documentation of OpenFileFlags
  System/Posix/IO/Common.hsc
Labels: documentation

#219 Fixes #35: fd{Read,Write} with ByteString payload (Breaking change)
  System/Posix/IO.hsc
  System/Posix/IO/ByteString.hsc
  System/Posix/IO/Common.hsc
Labels: API: breaking

#223 Expose DirStream and friends, fixes #25
  System/Posix/Directory/Internals.hsc
  unix.cabal
Labels: type: enhancement
